version: '3.9'
services:
  # app:
  #   image: llm-chainlit:latest
  #   ports:
  #     - "8000:8000"
  #   command: chainlit run -w /app/code/main-ui.py
  #   environment:
  #     - CHAINLIT_PORT=8000
  #     - CHAINLIT_HOST=0.0.0.0
  #   depends_on:
  #     - cloud-sql-proxy
  #     - init-db
  #   restart: always

  init-db:
    image: llm-chainlit:latest
    command: python /app/code/init_db.py
    depends_on:
      - cloud-sql-proxy
    restart: on-failure

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    command: /cloud_sql_proxy -instances=gen-project-427311:asia-southeast1:llm-stock-db=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/service_account.json
    ports:
      - 5432:5432
    volumes:
      - ./key:/secrets/cloudsql
    restart: always