services:
  app:
    image: llm-chainlit:latest
    env_file: .env
    ports:
      - "8000:8000"
    command: chainlit run -w /app/stock_analysis/main_ui.py
    environment:
      - CHAINLIT_PORT=8000
      - CHAINLIT_HOST=0.0.0.0
    depends_on:
      - cloud-sql-proxy
      - init-db
    restart: always

  init-db:
    image: llm-chainlit:latest
    env_file: .env
    command: python /app/stock_analysis/init_db.py
    depends_on:
      - cloud-sql-proxy
    restart: on-failure

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.0
    command: /cloud_sql_proxy -instances=${PROJECT_ID}:${REGION_NAME}:${DATABASE_NAME}=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/service_account.json
    volumes:
      - ./key:/secrets/cloudsql
    restart: always
