# Generated by CodiumAI
import sys
import os

# Get the absolute path of the current script
current_dir = os.path.dirname(os.path.abspath(__file__))

# Get the parent directory of 'tests'
project_root = os.path.dirname(os.path.dirname(current_dir))

# Add the project root to the Python path
sys.path.insert(0, project_root)
